; PlatformIO Project Configuration
[env:esp32-p4]
platform = espressif32@6.4.0
board = esp32-p4-function-evse
framework = espidf

monitor_speed = 115200

build_flags = 
    -DCONFIG_ESP32P4_DSI_HOST=y
    -DCONFIG_LVGL_9=y

lib_deps = 
    lvgl/lvgl@^9.0.0

upload_speed = 921600
